/**
 * ViewMarket Core Platform Knowledge Base & Identity Specification
 * Covers: What ViewMarket is, registration status, capabilities, and non-custodial model.
 */

export interface KnowledgeItem {
  id: string
  topic: string
  content: string
}

export const ABOUT_VIEWMARKET: KnowledgeItem[] = [
  {
    id: "identity_non_broker",
    topic: "Are we a broker or SEBI registered?",
    content:
      "ViewMarket is NOT a stockbroker, portfolio manager, or SEBI-registered investment advisor (RIA) or research analyst (RA). ViewMarket is a pure non-custodial software technology platform. We do not hold client funds, custody securities, or execute autonomous trades on behalf of users.",
  },
  {
    id: "byoa_model",
    topic: "How does trading work? (BYOA Model)",
    content:
      "ViewMarket operates on a Bring-Your-Own-Account (BYOA) architecture. Users connect their own existing demat/trading accounts via authorized broker APIs: Zerodha (Kite Connect v3), Angel One (SmartAPI v2), Upstox (API v2), Dhan (DhanHQ), Fyers (API v3), Kotak Neo (Trade API), ICICI Direct (Breeze API), and Shoonya by Finvasia (Noren API). All trade executions occur directly inside the user's personal brokerage account.",
  },
  {
    id: "mandatory_click_to_trade",
    topic: "Can ViewMarket place trades automatically?",
    content:
      "No. In compliance with Indian exchange and regulatory guidelines, ViewMarket enforces mandatory human-in-the-loop 'Click-to-Trade' confirmation. Every strategy signal generated by the platform or AI assistant requires explicit user review and confirmation before being dispatched to the broker API.",
  },
  {
    id: "platform_capabilities",
    topic: "What capabilities and features does ViewMarket provide?",
    content:
      "ViewMarket provides systematic strategy building, visual rule translation (NLP to structured logic), technical chart analytics, backtesting compute-as-a-service, real-time risk parameter enforcement, and multi-broker API connection gateways with zero server-side auth token persistence.",
  },
  {
    id: "sebi_fo_disclosure",
    topic: "Derivatives (F&O) risk warning",
    content:
      "Mandatory SEBI Disclosure: 9 out of 10 individual traders in equity futures and options (F&O) segment incur net financial losses. Past algorithmic performance or backtested metrics do not guarantee future returns.",
  },
]

/**
 * Returns formatted context string of all core 'About Us' knowledge items
 */
export function getAboutUsContext(): string {
  return ABOUT_VIEWMARKET.map((k) => `[Topic: ${k.topic}]\n${k.content}`).join("\n\n")
}
